#!/bin/sh

kwriteconfig6 --file breezerc --group Common --key OutlineCloseButton false
kwriteconfig6 --file breezerc --group Windeco --key ButtonSize ButtonSmall

kwriteconfig6 --file gwenviewrc --group SideBar --key "IsVisible ViewMode" false

kwriteconfig6 --file kcminputrc --group Keyboard --key KeyRepeat repeat
kwriteconfig6 --file kcminputrc --group Keyboard --key NumLock 2
kwriteconfig6 --file kcminputrc --group Keyboard --key RepeatDelay 300
kwriteconfig6 --file kcminputrc --group Keyboard --key RepeatRate 30
kwriteconfig6 --file kcminputrc --group Mouse --key XLbInptPointerAcceleration 0.4
kwriteconfig6 --file kcminputrc --group Mouse --key cursorTheme OSX-ElCap

kwriteconfig6 --file kcookiejarrc --group "Cookie Policy" --key CookieGlobalAdvice Reject

kwriteconfig6 --file kded5rc --group Module-device_automounter --key autoload false

kwriteconfig6 --file kdeglobals --group General --key "AllowKDEAppsToRememberWindowPositions" "false"
kwriteconfig6 --file kdeglobals --group General --key "BrowserApplication" "custom-chromium-default.desktop"
kwriteconfig6 --file kdeglobals --group General --key "ColorScheme" "Reactionary"
kwriteconfig6 --file kdeglobals --group General --key "Name" "Reactionary"
kwriteconfig6 --file kdeglobals --group General --key "UseSystemBell" "true"
kwriteconfig6 --file kdeglobals --group General --key "XftHintStyle" "hintslight"
kwriteconfig6 --file kdeglobals --group General --key "XftSubPixel" "rgb"
kwriteconfig6 --file kdeglobals --group General --key "fixed" "Source Code Pro,11,-1,5,57,0,0,0,0,0,Medium"
kwriteconfig6 --file kdeglobals --group General --key "font" "Fira Sans,11,-1,5,50,0,0,0,0,0"
kwriteconfig6 --file kdeglobals --group General --key "menuFont" "Fira Sans,11,-1,5,50,0,0,0,0,0"
kwriteconfig6 --file kdeglobals --group General --key "shadeSortColumn" "true"
kwriteconfig6 --file kdeglobals --group General --key "smallestReadableFont" "Fira Sans,9,-1,5,50,0,0,0,0,0"
kwriteconfig6 --file kdeglobals --group General --key "toolBarFont" "Fira Sans,11,-1,5,51,0,0,0,0,0"
kwriteconfig6 --file kdeglobals --group General --key "widgetStyle" "Reactionary"
kwriteconfig6 --file kdeglobals --group Icons --key "Theme" "SE98"
kwriteconfig6 --file kdeglobals --group KDE --key "AnimationDurationFactor" "0.25"
kwriteconfig6 --file kdeglobals --group KDE --key "ColorScheme" "Reactionary"
kwriteconfig6 --file kdeglobals --group KDE --key "ShowDeleteCommand" "false"
kwriteconfig6 --file kdeglobals --group KDE --key "SingleClick" "false"
kwriteconfig6 --file kdeglobals --group KDE --key "contrast" "4"
kwriteconfig6 --file kdeglobals --group KDE --key "widgetStyle" "Windows"
kwriteconfig6 --file kdeglobals --group WM --key "activeFont" "Fira Sans,11,-1,5,57,0,0,0,0,0,Medium"

kwriteconfig6 --file klaunchrc --group BusyCursorSettings --key Bouncing false
kwriteconfig6 --file klaunchrc --group FeedbackStyle --key BusyCursor false

kwriteconfig6 --file klipperrc --group General --key KeepClipboardContents false
kwriteconfig6 --file klipperrc --group General --key MaxClipItems 1

kwriteconfig6 --file konsolerc --group "Desktop Entry" --key DefaultProfile "My Default.profile"
kwriteconfig6 --file konsolerc --group KonsoleWindow --key ShowMenuBarByDefault false
kwriteconfig6 --file konsolerc --group KonsoleWindow --key SaveGeometryOnExit false
kwriteconfig6 --file konsolerc --group MainWindow --key MenuBar disabled
kwriteconfig6 --file konsolerc --group MainWindow --key StatusBar disabled
kwriteconfig6 --file konsolerc --group MainWindow --key ToolBarsMovable disabled

kwriteconfig6 --file kscreenlockerrc --group Daemon --key LockGrace 2
kwriteconfig6 --file kscreenlockerrc --group Daemon --key Timeout 15
kwriteconfig6 --file kscreenlockerrc --group Greeter --group Wallpaper --group org.kde.image --group General --key Image ~/"Pictures/Backgrounds/sunset_in_the_cascades.jpg"

kwriteconfig6 --file ksmserverrc --group General --key loginMode emptySession

kwriteconfig6 --file kwinrc --group Effect-DesktopGrid --key LayoutMode 1
kwriteconfig6 --file kwinrc --group Effect-PresentWindows --key LayoutMode 2
kwriteconfig6 --file kwinrc --group Effect-desktopgrid --key DesktopLayoutMode 1
kwriteconfig6 --file kwinrc --group Effect-overview --key LayoutMode 0
kwriteconfig6 --file kwinrc --group Effect-windowview --key LayoutMode 0
kwriteconfig6 --file kwinrc --group NightColor --key Active true
kwriteconfig6 --file kwinrc --group NightColor --key Mode Times
kwriteconfig6 --file kwinrc --group NightColor --key NightTemperature 3000
kwriteconfig6 --file kwinrc --group NightColor --key MorningBeginFixed 0700
kwriteconfig6 --file kwinrc --group NightColor --key EveningBeginFixed 1600
kwriteconfig6 --file kwinrc --group Plugins --key blurEnabled false
kwriteconfig6 --file kwinrc --group Plugins --key contractEnabled false
kwriteconfig6 --file kwinrc --group Plugins --key kwin4_effect_translucencyEnabled false
kwriteconfig6 --file kwinrc --group Plugins --key kwin4_effect_windowapertureEnabled false
kwriteconfig6 --file kwinrc --group Plugins --key zoomEnabled false
kwriteconfig6 --file kwinrc --group TabBox --key DelayTime 0
kwriteconfig6 --file kwinrc --group TabBox --key LayoutName compact
kwriteconfig6 --file kwinrc --group Windows --key DelayFocusInterval 0
kwriteconfig6 --file kwinrc --group Windows --key Placement Centered
kwriteconfig6 --file kwinrc --group org.kde.kdecoration2 --key ButtonsOnLeft M
kwriteconfig6 --file kwinrc --group org.kde.kdecoration2 --key library "org.kde.kwin.aurorae"
kwriteconfig6 --file kwinrc --group org.kde.kdecoration2 --key theme "__aurorae__svg__Reactionary"

kwriteconfig6 --file kxkbrc --group Layout --key "DisplayNames" ","
kwriteconfig6 --file kxkbrc --group Layout --key "LayoutList" "us,se"
kwriteconfig6 --file kxkbrc --group Layout --key "LayoutLoopCount" -- "-1"
kwriteconfig6 --file kxkbrc --group Layout --key "Model" "pc86"
kwriteconfig6 --file kxkbrc --group Layout --key "Options" "nodeadkeys,lv3:ralt_switch,ctrl:nocaps"
kwriteconfig6 --file kxkbrc --group Layout --key "ResetOldOptions" "false"
kwriteconfig6 --file kxkbrc --group Layout --key "SwitchMode" "Window"
kwriteconfig6 --file kxkbrc --group Layout --key "Use" "true"
kwriteconfig6 --file kxkbrc --group Layout --key "VariantList" "altgr-intl,"

kwriteconfig6 --file plasma-localerc --group Formats --key "LANG" "en_US.UTF-8"
kwriteconfig6 --file plasma-localerc --group Formats --key "LC_COLLATE" "sv_SE.UTF-8"
kwriteconfig6 --file plasma-localerc --group Formats --key "LC_MEASUREMENT" "sv_SE.UTF-8"
kwriteconfig6 --file plasma-localerc --group Formats --key "LC_MONETARY" "sv_SE.UTF-8"
kwriteconfig6 --file plasma-localerc --group Formats --key "LC_NUMERIC" "sv_SE.UTF-8"
kwriteconfig6 --file plasma-localerc --group Formats --key "LC_TIME" "sv_SE.UTF-8"
kwriteconfig6 --file plasma-localerc --group Formats --key "useDetailed" "true"

kwriteconfig6 --file plasmarc --group Theme --key name "Reactionary"
kwriteconfig6 --file plasmarc --group Wallpapers --key usersWallpapers ~/"Pictures/Backgrounds/sunset_in_the_cascades.jpg"

qdbus6 org.kde.KWin /KWin reconfigure
kquitapp6 kglobalaccel && sleep 1s && kstart /usr/lib/kglobalacceld &
