#!/bin/sh

defaults write -g AppleAccentColor                         -int    3
defaults write -g AppleAquaColorVariant                    -int    1
defaults write -g AppleHighlightColor                      -string "0.752941 0.964706 0.678431 Green"
defaults write -g AppleInterfaceStyleSwitchesAutomatically -bool   true
defaults write -g AppleLanguages                           -array  "en-US" "sv-SE"
defaults write -g AppleShowAllExtensions                   -bool   true
defaults write -g AppleShowScrollBars                      -string Always
defaults write -g AppleSpacesSwitchOnActivate              -bool   false
defaults write -g InitialKeyRepeat                         -int    15
defaults write -g KeyRepeat                                -int    2
defaults write -g NSAutomaticCapitalizationEnabled         -bool   false
defaults write -g NSAutomaticInlinePredictionEnabled       -bool   false
defaults write -g NSAutomaticSpellingCorrectionEnabled     -bool   false
defaults write -g NSWindowShouldDragOnGesture              -bool   true

defaults write -g com.apple.keyboard.fnState     -bool  true
defaults write -g com.apple.mouse.linear         -bool  true
defaults write -g com.apple.mouse.scaling        -int   2
defaults write -g com.apple.scrollwheel.scaling  -float 0.75
defaults write -g com.apple.springing.delay      -float 0.5
defaults write -g com.apple.springing.enabled    -int   1
defaults write -g com.apple.swipescrolldirection -int   0
defaults write -g com.apple.trackpad.forceClick  -int   1

defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores     -bool true

defaults write com.apple.finder FXPreferredViewStyle         -string Nlsv
defaults write com.apple.finder ShowPathbar                  -bool   true
defaults write com.apple.finder _FXSortFoldersFirstOnDesktop -bool   true

# Deactivate Apple Intelligence
defaults write com.apple.CloudSubscriptionFeatures.optIn 545129924 -bool false

defaults write com.apple.WindowManager EnableStandardClickToShowDesktop -bool false
defaults write com.apple.WindowManager EnableTiledWindowMargins         -bool false
